### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by mkborregaard** [JuliaGeo/meta#1]
Hi,
is it possible somewhere to find an overview of how to work with geographical data in Julia, and what functionality is implemented? Thanks a bunch!

**Comment by visr** [comment]
Cross ref https://discourse.julialang.org/t/overview-of-geo-tools/1844

**Comment by mkborregaard** [comment]
That's right, I realized that the julia-geo mailing list had migrated to discourse, posted my question there instead, then came here to delete the issue because I thought the discourse post was more appropriate. When I couldn't delete it I just closed the issue. Thanks for adding the x-ref.

**Comment by visr** [comment]
No worries, thanks for posting on discourse. I'll add a response later if no one beats me to it.

Not sure how others see the function of this meta repo exactly, but I suppose it is more geared to the JuliaGeo github org, whilst https://discourse.julialang.org/c/domain/geo is for broader discussion.
