### ISSUE TITLE
Updated links to wiki 

### ISSUE THREAD

**Issue by pritamd47** [JuliaGeo/meta#10]
Here is the link to my forked wiki repo: [updated wiki](https://github.com/pritamd47/meta.wiki.git).

If needed please refer to this [link](https://gist.github.com/larrybotha/10650410) for info on merging the changes to the wiki. I don't think there is a direct way to merge using pull requests.

Regards,
Pritam

**Comment by yeesian** [comment]
I'm sorry I made this harder for you than it should have been. Updating the wiki should not be this hard for contributors (and merging the suggestions should not have been this hard). I've [migrated the pages from the wiki to markdown files in the repository](https://github.com/JuliaGeo/meta/pull/11) to make it easier in the future, and made your suggested changes in https://github.com/JuliaGeo/meta/pull/12.

**Comment by yeesian** [comment]
And many thanks for your contribution! :)
