### ISSUE TITLE
Moving new package GADM.jl to JuliaGeo

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/meta#14]
I've mentored Aayush Joglekar over the last weeks as part of the MLH fellowship program, and he wrote a very useful package for querying polygons given any named region in the world (country, state, district, city, ...). The package is built on top of the amazing https://gadm.org effort, and I am planning to move the repository to JuliaGeo this week. Please let me know if you feel that the package should be placed somewhere else instead.

Link to the project: https://github.com/zerefwayne/GADM.jl

cc: @zerefwayne

**Comment by visr** [comment]
Congrats both on creating this package! I've used GADM in the past and it's quite a handy dataset. And the API of this package looks very convenient. I think it would be good to move this package to Julia, though I have a few points:

- The GADM dataset has a rather restrictive non-commercial license; https://gadm.org/license.html. Perhaps it would be good to mention this license in the GADM.jl readme? Perhaps even with a link to the Natural Earth dataset, [which is public domain](https://www.naturalearthdata.com/about/terms-of-use/).
- I see GADM.jl has an ISC license. I know that functionally it is pretty much identical to MIT, but I think [to reduce license proliferation](https://op.europa.eu/en/web/eu-vocabularies/at-concept/-/resource/authority/licence/ISC/) it would be better to just use MIT instead, like all of the rest of the JuliaGeo packages. And likely an oversight, but Aayush should probably add his own name to the copyright holders as well :)
- Currently the tests seem to fail sometimes? Would be good to make sure the testing suite is sufficiently robust.

**Comment by juliohm** [comment]
Nice! Let's proceed with the migration over the week :+1: 

> * The GADM dataset has a rather restrictive non-commercial license; https://gadm.org/license.html. Perhaps it would be good to mention this license in the GADM.jl readme? Perhaps even with a link to the Natural Earth dataset, [which is public domain](https://www.naturalearthdata.com/about/terms-of-use/).

I think @zerefwayne had looked into Natural Earth too. We should consider writing another package for it in the future.

> * I see GADM.jl has an ISC license. I know that functionally it is pretty much identical to MIT, but I think [to reduce license proliferation](https://op.europa.eu/en/web/eu-vocabularies/at-concept/-/resource/authority/licence/ISC/) it would be better to just use MIT instead, like all of the rest of the JuliaGeo packages. And likely an oversight, but Aayush should probably add his own name to the copyright holders as well :)

@zerefwayne I didn't notice you added my name in the LICENSE instead of yours! Your name should be listed there instead of mine. You created the package in your account and did all the coding, I just reviewed and polished a few things. Can you also change the license to MIT as suggested?

> * Currently the tests seem to fail sometimes? Would be good to make sure the testing suite is sufficiently robust.

@zerefwayne I remember we having connection issues with GADM sometimes because their server was down. If you can confirm that the tests are failing just because of that, it would be great.

**Comment by zerefwayne** [comment]
Thank you @visr! I would like to address the 3rd point. The server which hosts the dataset goes down (probably for maintenance) once or twice a week for a brief period. This causes the TravisCI to fail because it cannot procure the dataset. Apart from that issue, the test coverage is 100% and will make sure to keep it as high in the future.

This server downtime issue will not be a problem for users since our package persists the dataset once downloaded on the user's system. I'll add a feature to let users know if the server is down.

**Comment by zerefwayne** [comment]
@juliohm @visr 

I have updated the LICENSE! Ready to go. :champagne:

**Comment by visr** [comment]
Thanks! Too bad the server goes down regularly, but there is little we can do about that. Luckily a download is only needed once.

**Comment by meggart** [comment]
Thanks a lot for creating the package and +1 for moving to JuliaGeo

**Comment by juliohm** [comment]
Package moved and in waiting the registration process! :champagne:
