### ISSUE TITLE
TagBot failures

### ISSUE THREAD

**Issue by visr** [JuliaGeo/meta#17]
To reduce noise, I am unsubscribed from all TagBot trigger issues, but today @juliohm mentioned here https://github.com/JuliaGeo/GADM.jl/issues/31#issuecomment-1013674699 that TagBot has been failing in multiple (all?) JuliaGeo repositories for a while, so whilst new releases were registered just fine, these tags are not visible on GitHub.

Looking at the TagBot logs: https://github.com/JuliaGeo/GADM.jl/runs/4827591992?check_suite_focus=true

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Access rights are currently given as:
```yaml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
```

[see for example this file](https://github.com/JuliaGeo/GADM.jl/blob/faaf20367893a8db67f10a390957bfec88f56b2e/.github/workflows/TagBot.yml#L12-L15).

My interpretation based on https://github.com/pre-commit/action/issues/8 is that it is trying to use the SSH key `DOCUMENTER_KEY`, but this doesn't work, maybe because GitHub is now more strict: https://github.blog/2021-09-01-improving-git-protocol-security-github/.

As written in the [Documenter docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions) we can use [`DocumenterTools.genkeys`](https://github.com/JuliaDocs/DocumenterTools.jl/blob/8febf07baf256488fde8df557e62de21bf2aae3a/src/genkeys.jl#L15-L57) to create new keys and add new DOCUMENTER_KEY secret environment variables. As far as I can see that has to be done for each repository individually.

Is this the right course of action do you think?

**Comment by visr** [comment]
I went ahead and added documenter SSH keys to each repo, with corresponding `DOCUMENTER_KEY` secrets. This seems to have worked, TagBot no longer gets a 'permission denied' error. For GADM.jl and GeoInterface.jl I saw that it still added tags that were missed before. However for GDAL.jl this was not the case, TagBot said 'No new versions to release'.

Though then I saw that this must be due to the default [lookback period](https://github.com/JuliaRegistries/TagBot#lookback-period) of 3 days, and GDAL.jl was released 5 days ago. So in a branch I committed a lookback period of 30 days (https://github.com/JuliaGeo/GDAL.jl/commit/58a071a9810f2bc703693b014b9fc1774059326e), ran the TagBot action on that branch, and voila, two new tagged releases, https://github.com/JuliaGeo/GDAL.jl/releases/tag/v1.3.0. I don't want to go over all repos to check if there are more missing tags from the last few months, but if there are, you can use the same process to still get them (or do it manually).

**Comment by meggart** [comment]
A big thank you for taking the time to add Documenter Keys to all repos. As you mentioned, in quite a few packages the CompatHelper workflow is a bit outdated and I will run a MassInstallationAction to update it for all repos.

**Comment by meggart** [comment]
I just tried the MassInstallAction with a fresh Github access token but it failed due to problems with authentication when running the action. I will try again later today, don't really have time to investigate now.

**Comment by visr** [comment]
Ok, if it doesn't work, perhaps show what you tried, then I can give it a shot as well.

**Comment by meggart** [comment]
Ok, I fixed it. Had to do a small change to MassInstallAction to make it use ssh instead of https when pushing the branch so it works with 2FA. I think all we need to do is to accept the created PRs to have the most recent CompatHelper workflow.

**Comment by visr** [comment]
Great, thanks! I went ahead and merged all the PRs.
