### ISSUE TITLE
JuliaGeo in a Docker Container

### ISSUE THREAD

**Issue by ratnanil** [JuliaGeo/meta#19]
Before I start building my own, is there a Docker Container containing all the JuliaGeo libraries?

**Comment by visr** [comment]
Not to my knowledge, no. There are general julia ones over at https://hub.docker.com/_/julia. Just out of interest, what is your intended use case? I know some people like to combine docker with https://github.com/JuliaLang/PackageCompiler.jl/ to get containerized applications that start quickly.

**Comment by ratnanil** [comment]
Thanks for the advice, I'll definitely check it out!

In regard to your question about my use case: I come from R/python and have made it a habit to work in docker containers. E.g. for geospatialstuff in R, I build on top of [rocker/geospatial](https://hub.docker.com/r/rocker/geospatial), which is a one stop shop for all things geospatial in R. I was looking for something similar to get started in Julia.
