### ISSUE TITLE
Add dependabot to all JuliaGeo packages

### ISSUE THREAD

**Issue by visr** [JuliaGeo/meta#20]
We mostly use GitHub Actions for CI. However many of the actions we use are deprecated. Dependabot can automatically submit PRs to keep them up to date. It is probably a good idea to add this to all JuliaGeo packages, I think currently only GDAL.jl uses it.

Came up in https://github.com/JuliaGeo/GeoJSON.jl/issues/69

**Comment by yeesian** [comment]
> However many of the actions we use are deprecated. Dependabot can automatically submit PRs to keep them up to date.

Who's gonna watch the watchmen 👀

**Comment by visr** [comment]
Awesome, thanks for the action @yeesian! I guess that was all? If so this can be closed.
