### ISSUE TITLE
Minimum julia version to v0.6?

### ISSUE THREAD

**Issue by visr** [JuliaGeo/meta#3]
All packages here still have v0.5 in their REQUIRE on master.
Anyone opposed to me setting them all to v0.6, letting [FemtoCleaner](https://github.com/JuliaComputing/FemtoCleaner.jl) fix deprecations, and [attobot](https://github.com/attobot/attobot) tag a new release?

Should make it a bit less work to maintain, and closer to working on master.

**Comment by visr** [comment]
Didn't get to tag versions anymore, feel free to do so instead. I'll be away for a few weeks.

**Comment by yeesian** [comment]
Thanks for all your work on this, it's been really helpful!
