### ISSUE TITLE
Minimum julia version to v0.7.0-beta?

### ISSUE THREAD

**Issue by visr** [JuliaGeo/meta#4]
Copy of #3 but now a bit earlier. But is it too early?

All packages here still have v0.6 in their REQUIRE on master.
Anyone opposed to me setting them all to v0.7, letting FemtoCleaner fix deprecations, and attobot tag a new release? I believe this will be less work than continue to support both v0.6 and v0.7, plus we can't use FemtoCleaner.

We can still release bugfixes on a julia v0.6 branch of course.

**Comment by yeesian** [comment]
> Anyone opposed to me setting them all to v0.7, letting FemtoCleaner fix deprecations, and attobot tag a new release?

Sounds good to me!

**Comment by visr** [comment]
Closing. Since about two weeks ago all JuliaGeo packages should work on 0.7 and 1.0, and are tagged.
