### ISSUE TITLE
start using CompatHelper.jl

### ISSUE THREAD

**Issue by visr** [JuliaGeo/meta#8]
I'd like to propose installing CompatHelper in all packages under JuliaGeo.

The General registry started suggesting strongly that packages add upper bounds on the versions of their dependencies. The upside of this is that if a dependency does a breaking release, it won't break your package due to the upper bound holding it back. A downside is that this will prevent updating to shiny new versions, even if they actually don't break your package at all.

To help with this downside Dilum Aluthge created CompatHelper.jl: https://github.com/bcbi/CompatHelper.jl.

When a dependency does a breaking release, it will automatically open a PR to update the bounds and see if it is actually breaking. If it is not, the idea is to merge the PR and tag a new release, such that we will not be stuck with many old packages if we want to use many packages in the same Pkg environment.

Any concerns? Otherwise I'll start pushing it to the repositories sometime soon.

**Comment by mauro3** [comment]
I tried it on one of my repos so far and it seems to do what it says. +1

**Comment by visr** [comment]
Ok, closing this. Went through them and applied it to all packages that have non stdlib dependencies.
